In [7]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [8]:
df = pd.read_csv("styles.csv", on_bad_lines="skip")

In [9]:
df = df[['id', 'articleType']]
df.head()

      id  articleType
0  15970       Shirts
1  39386        Jeans
2  59263      Watches
3  21379  Track Pants
4  53759      Tshirts

In [10]:
image_folder = "images"

df["image_path"] = df["id"].astype(str) + ".jpg"

df["image_path"] = df["image_path"].apply(
    lambda x: os.path.join(image_folder, x)
)

df.head()

      id  articleType        image_path
0  15970       Shirts  images\15970.jpg
1  39386        Jeans  images\39386.jpg
2  59263      Watches  images\59263.jpg
3  21379  Track Pants  images\21379.jpg
4  53759      Tshirts  images\53759.jpg

In [11]:
df["exists"] = df["image_path"].apply(os.path.exists)

print(df["exists"].value_counts())

exists
False    44424
Name: count, dtype: int64

In [12]:
df["exists"].value_counts()

exists
False    44424
Name: count, dtype: int64